import { useState } from "react";
import { Link, useSearchParams } from "react-router-dom";
import { confirmPasswordReset } from "../api.js";

export default function ResetPassword() {
  const [params] = useSearchParams(); const [password, setPassword] = useState(""); const [confirm, setConfirm] = useState(""); const [message, setMessage] = useState(""); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  const submit = async e => { e.preventDefault(); setLoading(true); setError(""); try { const data = await confirmPasswordReset({ uid: params.get("uid"), token: params.get("token"), new_password: password, confirm_password: confirm }); setMessage(data.detail); } catch (e) { setError(e.message); } finally { setLoading(false); } };
  return <div className="flex min-h-screen items-center justify-center bg-slate-100 p-4"><div className="w-full max-w-md rounded-2xl bg-white p-7 shadow-lg"><h1 className="text-2xl font-bold">Set a new password</h1><p className="mb-6 mt-1 text-sm text-slate-500">Choose a new password for your account.</p>{message ? <div className="space-y-4"><p className="rounded-lg bg-emerald-50 p-3 text-sm text-emerald-700">{message}</p><Link to="/login" className="block text-center font-medium text-indigo-600">Go to login</Link></div> : <form onSubmit={submit} className="space-y-4"><label className="block text-sm font-medium">New password<input required minLength="8" type="password" value={password} onChange={e => setPassword(e.target.value)} className="mt-1 w-full rounded-lg border px-3 py-2.5" /></label><label className="block text-sm font-medium">Confirm password<input required minLength="8" type="password" value={confirm} onChange={e => setConfirm(e.target.value)} className="mt-1 w-full rounded-lg border px-3 py-2.5" /></label>{error && <p className="rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}<button disabled={loading || !params.get("uid") || !params.get("token")} className="w-full rounded-lg bg-indigo-600 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-60">{loading ? "Updating..." : "Reset password"}</button></form>}</div></div>;
}
